# Generated by Django 2.1.5 on 2021-07-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='meet_who',
        ),
        migrations.AddField(
            model_name='task',
            name='share',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
