# Generated by Django 2.1.5 on 2021-07-31 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210731_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='share',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
