# Generated by Django 2.1.5 on 2021-08-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20210806_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('fazendo', 'Fazendo'), ('feito', 'Feito')], max_length=7),
        ),
    ]
